[tool.poetry]
name = "code-names-bot-oxford-downloader"
version = "0.1.0"
description = ""
authors = ["Nalu Zou <zonalu@amazon.com>"]

[tool.poetry.dependencies]
python = "^3.7"
nltk = "^3.7"
black = "^22.6.0"
isort = "^5.10.1"
tqdm = "^4.64.0"
wordfreq = "^3.0.1"
requests = "^2.28.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
format                  = "tasks:format"
setup                   = "tasks:setup"

get-word-freq           = "tools.get_word_freq:main"

create-lemma-list       = "code_names_bot_oxford_downloader.create_lemma_list:main"
downloader              = "code_names_bot_oxford_downloader.downloader:main"
word-list-scraper       = "code_names_bot_oxford_downloader.word_list_scraper:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
