[tool.poetry]
name = "code-names-bot-oxford-downloader"
version = "0.1.0"
description = ""
authors = ["Nalu Zou <zonalu@amazon.com>"]

[tool.poetry.dependencies]
python = "^3.7"
nltk = "^3.7"
black = "^22.6.0"
isort = "^5.10.1"
tqdm = "^4.64.0"
wordfreq = "^3.0.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
